"""Type stubs for the native ``pydocstring._pydocstring`` extension module.

Parses Google-style and NumPy-style Python docstrings into typed, traversable
objects with source-location information suitable for linters and formatters.
"""

from __future__ import annotations

from typing import TypeVar

from ._visitor import Visitor

_VisitorT = TypeVar("_VisitorT", bound="Visitor")

# ─── Core types ──────────────────────────────────────────────────────────────

class TextRange:
    """Byte range ``[start, end)`` within the source string."""

    start: int
    end: int
    def is_empty(self) -> bool:
        """Return ``True`` when ``start == end`` (zero-length placeholder)."""
        ...
    def __repr__(self) -> str: ...

class LineColumn:
    """1-based line number and 0-based column offset."""

    lineno: int
    col: int
    def __repr__(self) -> str: ...

class WalkContext:
    """Context passed to every ``enter_*`` method during a ``walk()`` call."""
    def line_col(self, offset: int) -> LineColumn: ...
    def __repr__(self) -> str: ...

class Token:
    """A text fragment plus its source byte range.  Has no ``kind`` field."""
    @property
    def text(self) -> str: ...
    @property
    def range(self) -> TextRange: ...
    def is_missing(self) -> bool:
        """Return ``True`` when this token is a zero-length placeholder.

        The parser inserts missing tokens for syntactically absent elements
        such as the type in ``arg ():`` or a missing closing parenthesis.
        Equivalent to ``token.range.is_empty()``.
        """
        ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class Style:
    """Docstring style detected or used for emission."""

    GOOGLE: Style
    NUMPY: Style
    PLAIN: Style
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

# ─── Section kinds ───────────────────────────────────────────────────────────

class GoogleSectionKind:
    ARGS: GoogleSectionKind
    KEYWORD_ARGS: GoogleSectionKind
    OTHER_PARAMETERS: GoogleSectionKind
    RECEIVES: GoogleSectionKind
    RETURNS: GoogleSectionKind
    YIELDS: GoogleSectionKind
    RAISES: GoogleSectionKind
    WARNS: GoogleSectionKind
    ATTRIBUTES: GoogleSectionKind
    METHODS: GoogleSectionKind
    SEE_ALSO: GoogleSectionKind
    NOTES: GoogleSectionKind
    EXAMPLES: GoogleSectionKind
    TODO: GoogleSectionKind
    REFERENCES: GoogleSectionKind
    WARNINGS: GoogleSectionKind
    ATTENTION: GoogleSectionKind
    CAUTION: GoogleSectionKind
    DANGER: GoogleSectionKind
    ERROR: GoogleSectionKind
    HINT: GoogleSectionKind
    IMPORTANT: GoogleSectionKind
    TIP: GoogleSectionKind
    UNKNOWN: GoogleSectionKind
    def __repr__(self) -> str: ...

class NumPySectionKind:
    PARAMETERS: NumPySectionKind
    RETURNS: NumPySectionKind
    YIELDS: NumPySectionKind
    RECEIVES: NumPySectionKind
    OTHER_PARAMETERS: NumPySectionKind
    RAISES: NumPySectionKind
    WARNS: NumPySectionKind
    WARNINGS: NumPySectionKind
    SEE_ALSO: NumPySectionKind
    NOTES: NumPySectionKind
    REFERENCES: NumPySectionKind
    EXAMPLES: NumPySectionKind
    ATTRIBUTES: NumPySectionKind
    METHODS: NumPySectionKind
    UNKNOWN: NumPySectionKind
    def __repr__(self) -> str: ...

# ─── Google CST wrappers ─────────────────────────────────────────────────────

class GoogleArg:
    @property
    def range(self) -> TextRange: ...
    @property
    def name(self) -> Token: ...
    @property
    def open_bracket(self) -> Token | None: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def close_bracket(self) -> Token | None: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    @property
    def optional(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class GoogleReturn:
    @property
    def range(self) -> TextRange: ...
    @property
    def return_type(self) -> Token | None: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class GoogleYield:
    @property
    def range(self) -> TextRange: ...
    @property
    def return_type(self) -> Token | None: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class GoogleException:
    @property
    def range(self) -> TextRange: ...
    @property
    def type(self) -> Token: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class GoogleWarning:
    @property
    def range(self) -> TextRange: ...
    @property
    def warning_type(self) -> Token: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class GoogleSeeAlsoItem:
    @property
    def range(self) -> TextRange: ...
    @property
    def names(self) -> list[Token]: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class GoogleAttribute:
    @property
    def range(self) -> TextRange: ...
    @property
    def name(self) -> Token: ...
    @property
    def open_bracket(self) -> Token | None: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def close_bracket(self) -> Token | None: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class GoogleMethod:
    @property
    def range(self) -> TextRange: ...
    @property
    def name(self) -> Token: ...
    @property
    def open_bracket(self) -> Token | None: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def close_bracket(self) -> Token | None: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class GoogleSection:
    """A section in a Google-style docstring.

    Child nodes are not directly accessible; use :func:`walk` with a
    :class:`Visitor` to iterate over ``GoogleArg``, ``GoogleReturn``, etc.
    """
    @property
    def range(self) -> TextRange: ...
    @property
    def section_kind(self) -> GoogleSectionKind: ...
    @property
    def header_name(self) -> Token: ...
    def __repr__(self) -> str: ...

class GoogleDocstring:
    """A parsed Google-style docstring."""
    @property
    def range(self) -> TextRange: ...
    @property
    def summary(self) -> Token | None: ...
    @property
    def extended_summary(self) -> Token | None: ...
    @property
    def stray_lines(self) -> list[Token]: ...
    @property
    def sections(self) -> list[GoogleSection]: ...
    @property
    def source(self) -> str: ...
    @property
    def style(self) -> Style: ...
    def pretty_print(self) -> str: ...
    def to_model(self) -> Docstring: ...
    def __repr__(self) -> str: ...

# ─── NumPy CST wrappers ──────────────────────────────────────────────────────

class NumPyDeprecation:
    @property
    def range(self) -> TextRange: ...
    @property
    def directive_marker(self) -> Token | None: ...
    @property
    def keyword(self) -> Token | None: ...
    @property
    def double_colon(self) -> Token | None: ...
    @property
    def version(self) -> Token: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class NumPyParameter:
    @property
    def range(self) -> TextRange: ...
    @property
    def names(self) -> list[Token]: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    @property
    def optional(self) -> Token | None: ...
    @property
    def default_keyword(self) -> Token | None: ...
    @property
    def default_separator(self) -> Token | None: ...
    @property
    def default_value(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class NumPyReturns:
    """A single named return entry in a NumPy ``Returns`` section."""
    @property
    def range(self) -> TextRange: ...
    @property
    def name(self) -> Token | None: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def return_type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class NumPyYields:
    """A single named yield entry in a NumPy ``Yields`` section."""
    @property
    def range(self) -> TextRange: ...
    @property
    def name(self) -> Token | None: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def return_type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class NumPyException:
    @property
    def range(self) -> TextRange: ...
    @property
    def type(self) -> Token: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class NumPyWarning:
    @property
    def range(self) -> TextRange: ...
    @property
    def type(self) -> Token: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class NumPySeeAlsoItem:
    @property
    def range(self) -> TextRange: ...
    @property
    def names(self) -> list[Token]: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class NumPyReference:
    @property
    def range(self) -> TextRange: ...
    @property
    def directive_marker(self) -> Token | None: ...
    @property
    def open_bracket(self) -> Token | None: ...
    @property
    def number(self) -> Token | None: ...
    @property
    def close_bracket(self) -> Token | None: ...
    @property
    def content(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class NumPyAttribute:
    @property
    def range(self) -> TextRange: ...
    @property
    def name(self) -> Token: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def type(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class NumPyMethod:
    @property
    def range(self) -> TextRange: ...
    @property
    def name(self) -> Token: ...
    @property
    def colon(self) -> Token | None: ...
    @property
    def description(self) -> Token | None: ...
    def __repr__(self) -> str: ...

class NumPySection:
    """A section in a NumPy-style docstring.

    Child nodes are not directly accessible; use :func:`walk` with a
    :class:`Visitor` to iterate over ``NumPyParameter``, ``NumPyReturns``, etc.
    """
    @property
    def range(self) -> TextRange: ...
    @property
    def section_kind(self) -> NumPySectionKind: ...
    @property
    def header_name(self) -> Token: ...
    def __repr__(self) -> str: ...

class NumPyDocstring:
    """A parsed NumPy-style docstring."""
    @property
    def range(self) -> TextRange: ...
    @property
    def summary(self) -> Token | None: ...
    @property
    def extended_summary(self) -> Token | None: ...
    @property
    def deprecation(self) -> NumPyDeprecation | None: ...
    @property
    def sections(self) -> list[NumPySection]: ...
    @property
    def source(self) -> str: ...
    @property
    def style(self) -> Style: ...
    def pretty_print(self) -> str: ...
    def to_model(self) -> Docstring: ...
    def __repr__(self) -> str: ...

# ─── Plain CST wrapper ───────────────────────────────────────────────────────

class PlainDocstring:
    """A parsed plain docstring (no section markers)."""
    @property
    def range(self) -> TextRange: ...
    @property
    def summary(self) -> Token | None: ...
    @property
    def extended_summary(self) -> Token | None: ...
    @property
    def source(self) -> str: ...
    @property
    def style(self) -> Style: ...
    def pretty_print(self) -> str: ...
    def to_model(self) -> Docstring: ...
    def __repr__(self) -> str: ...

# ─── Model IR ────────────────────────────────────────────────────────────────

class Deprecation:
    version: str
    description: str | None
    def __init__(self, version: str, *, description: str | None = None) -> None: ...
    def __repr__(self) -> str: ...

class Parameter:
    names: list[str]
    type_annotation: str | None
    description: str | None
    is_optional: bool
    default_value: str | None
    def __init__(
        self,
        names: list[str],
        *,
        type_annotation: str | None = None,
        description: str | None = None,
        is_optional: bool = False,
        default_value: str | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class Return:
    name: str | None
    type_annotation: str | None
    description: str | None
    def __init__(
        self,
        *,
        name: str | None = None,
        type_annotation: str | None = None,
        description: str | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class ExceptionEntry:
    type_name: str
    description: str | None
    def __init__(self, type_name: str, *, description: str | None = None) -> None: ...
    def __repr__(self) -> str: ...

class SeeAlsoEntry:
    names: list[str]
    description: str | None
    def __init__(self, names: list[str], *, description: str | None = None) -> None: ...
    def __repr__(self) -> str: ...

class Reference:
    number: str | None
    content: str | None
    def __init__(self, *, number: str | None = None, content: str | None = None) -> None: ...
    def __repr__(self) -> str: ...

class Attribute:
    name: str
    type_annotation: str | None
    description: str | None
    def __init__(
        self,
        name: str,
        *,
        type_annotation: str | None = None,
        description: str | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class Method:
    name: str
    type_annotation: str | None
    description: str | None
    def __init__(
        self,
        name: str,
        *,
        type_annotation: str | None = None,
        description: str | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class SectionKind:
    """Style-independent section kind for the model IR."""

    PARAMETERS: SectionKind
    KEYWORD_PARAMETERS: SectionKind
    OTHER_PARAMETERS: SectionKind
    RECEIVES: SectionKind
    RETURNS: SectionKind
    YIELDS: SectionKind
    RAISES: SectionKind
    WARNS: SectionKind
    ATTRIBUTES: SectionKind
    METHODS: SectionKind
    SEE_ALSO: SectionKind
    REFERENCES: SectionKind
    NOTES: SectionKind
    EXAMPLES: SectionKind
    WARNINGS: SectionKind
    TODO: SectionKind
    ATTENTION: SectionKind
    CAUTION: SectionKind
    DANGER: SectionKind
    ERROR: SectionKind
    HINT: SectionKind
    IMPORTANT: SectionKind
    TIP: SectionKind
    UNKNOWN: SectionKind
    def __repr__(self) -> str: ...

class Section:
    """A section in the model IR."""
    @property
    def kind(self) -> SectionKind: ...
    @property
    def unknown_name(self) -> str | None: ...
    @property
    def parameters(self) -> list[Parameter]: ...
    @property
    def returns(self) -> list[Return]: ...
    @property
    def exceptions(self) -> list[ExceptionEntry]: ...
    @property
    def attributes(self) -> list[Attribute]: ...
    @property
    def methods(self) -> list[Method]: ...
    @property
    def see_also_entries(self) -> list[SeeAlsoEntry]: ...
    @property
    def references(self) -> list[Reference]: ...
    @property
    def body(self) -> str | None: ...
    def __init__(
        self,
        kind: SectionKind,
        *,
        unknown_name: str | None = None,
        parameters: list[Parameter] | None = None,
        returns: list[Return] | None = None,
        exceptions: list[ExceptionEntry] | None = None,
        attributes: list[Attribute] | None = None,
        methods: list[Method] | None = None,
        see_also_entries: list[SeeAlsoEntry] | None = None,
        references: list[Reference] | None = None,
        body: str | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class Docstring:
    """High-level docstring model used for emit / round-trip."""

    summary: str | None
    extended_summary: str | None
    deprecation: Deprecation | None
    sections: list[Section]
    def __init__(
        self,
        *,
        summary: str | None = None,
        extended_summary: str | None = None,
        deprecation: Deprecation | None = None,
        sections: list[Section] | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...

# ─── Functions ───────────────────────────────────────────────────────────────

def parse(input: str) -> GoogleDocstring | NumPyDocstring | PlainDocstring:
    """Auto-detect the style and parse ``input``.

    Check ``.style`` or use ``isinstance`` to distinguish the returned type.
    """
    ...

def parse_google(input: str) -> GoogleDocstring:
    """Parse ``input`` as a Google-style docstring."""
    ...

def parse_numpy(input: str) -> NumPyDocstring:
    """Parse ``input`` as a NumPy-style docstring."""
    ...

def parse_plain(input: str) -> PlainDocstring:
    """Parse ``input`` as a plain docstring (no section markers)."""
    ...

def detect_style(input: str) -> Style:
    """Detect the docstring style without fully parsing."""
    ...

def emit_google(doc: Docstring, base_indent: int = 0) -> str:
    """Render a model ``Docstring`` as Google-style text."""
    ...

def emit_numpy(doc: Docstring, base_indent: int = 0) -> str:
    """Render a model ``Docstring`` as NumPy-style text."""
    ...

def walk(
    doc: GoogleDocstring | NumPyDocstring | PlainDocstring,
    visitor: _VisitorT,
) -> _VisitorT:
    """Walk any docstring depth-first, calling typed methods on ``visitor``.

    Accepts a `GoogleDocstring`, `NumPyDocstring`, or `PlainDocstring`.
    Define only the ``enter_*`` methods you need; all others are silently skipped.
    Returns ``visitor`` so results can be collected inline.

    Every ``enter_*`` method receives ``(node, ctx: WalkContext)`` as arguments.
    Use ``ctx.line_col(offset)`` to convert byte offsets to line/column positions.

    .. code-block:: python

        class MyChecker:
            def enter_google_arg(self, arg: GoogleArg, ctx: WalkContext) -> None:
                lc = ctx.line_col(arg.range.start)
            def enter_numpy_parameter(self, param: NumPyParameter, ctx: WalkContext) -> None: ...

        for source_text in all_docstrings:
            doc = pydocstring.parse(source_text)
            checker = pydocstring.walk(doc, checker)  # returns visitor

    Google-style ``enter_*`` methods:

    .. code-block:: python

        def enter_google_docstring(self, doc: GoogleDocstring, ctx: WalkContext) -> None: ...
        def enter_google_section(self, section: GoogleSection, ctx: WalkContext) -> None: ...
        def enter_google_arg(self, arg: GoogleArg, ctx: WalkContext) -> None: ...
        def enter_google_return(self, ret: GoogleReturn, ctx: WalkContext) -> None: ...
        def enter_google_yield(self, yld: GoogleYield, ctx: WalkContext) -> None: ...
        def enter_google_exception(self, exc: GoogleException, ctx: WalkContext) -> None: ...
        def enter_google_warning(self, wrn: GoogleWarning, ctx: WalkContext) -> None: ...
        def enter_google_see_also_item(self, sai: GoogleSeeAlsoItem, ctx: WalkContext) -> None: ...
        def enter_google_attribute(self, att: GoogleAttribute, ctx: WalkContext) -> None: ...
        def enter_google_method(self, mtd: GoogleMethod, ctx: WalkContext) -> None: ...

    NumPy-style ``enter_*`` methods:

    .. code-block:: python

        def enter_numpy_docstring(self, doc: NumPyDocstring, ctx: WalkContext) -> None: ...
        def enter_numpy_section(self, section: NumPySection, ctx: WalkContext) -> None: ...
        def enter_numpy_deprecation(self, dep: NumPyDeprecation, ctx: WalkContext) -> None: ...
        def enter_numpy_parameter(self, param: NumPyParameter, ctx: WalkContext) -> None: ...
        def enter_numpy_returns(self, ret: NumPyReturns, ctx: WalkContext) -> None: ...
        def enter_numpy_yields(self, yld: NumPyYields, ctx: WalkContext) -> None: ...
        def enter_numpy_exception(self, exc: NumPyException, ctx: WalkContext) -> None: ...
        def enter_numpy_warning(self, wrn: NumPyWarning, ctx: WalkContext) -> None: ...
        def enter_numpy_see_also_item(self, sai: NumPySeeAlsoItem, ctx: WalkContext) -> None: ...
        def enter_numpy_reference(self, ref: NumPyReference, ctx: WalkContext) -> None: ...
        def enter_numpy_attribute(self, att: NumPyAttribute, ctx: WalkContext) -> None: ...
        def enter_numpy_method(self, mtd: NumPyMethod, ctx: WalkContext) -> None: ...

    Plain ``enter_*`` methods:

    .. code-block:: python

        def enter_plain_docstring(self, doc: PlainDocstring, ctx: WalkContext) -> None: ...
    """
    ...
